version: "3.8"
networks:
  mapstore-network:
    driver: bridge

services:
  postgres:
    image: rogalik/postgres
    container_name: postgres_mapstore
    restart: on-failure
    healthcheck:
      test: /usr/bin/pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geostore
    volumes:
    - pg_data:${PGDATA:-/var/lib/postgresql/data}:rw
    ports:
      - 5434:5432
    networks:
      - mapstore-network

  mapstore:
    image: rogalik/mapstore
    container_name: mapstore
    command: [ "wait-for-postgres", "postgres", "5432", "postgres", "postgres", "catalina.sh", "run" ]
    depends_on:
      - postgres
    ports:
      - 8080
    networks:
      - mapstore-network

  proxy:
    image: rogalik/nginx
    container_name: proxy
    volumes:
      - ./docker/mapstore.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - 8080:80
    depends_on:
      - mapstore
    networks:
      - mapstore-network
  
  geoserver:
    image: rogalik/geoserver
    container_name: geoserver
    ports:
      - "8085:8080"
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - EXTRA_JAVA_OPTS=-Xms1G -Xmx2G
      - POSTGRES_JNDI_ENABLED=true
      - POSTGRES_HOST=postgis
      - POSTGRES_PORT=5432
      - POSTGRES_DB=geoserver
      - POSTGRES_USERNAME=geoserver
      - POSTGRES_PASSWORD=geoserver
      - POSTGRES_JNDI_RESOURCE_NAME=jdbc/postgres
    volumes:
      - ./geoserver/geoserver_data:/opt/geoserver_data/:Z
      - ./geoserver/additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
    healthcheck:
      test: curl --fail "http://localhost:8085/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
      interval: 1m
      retries: 3
      timeout: 20s
    networks:
      - mapstore-network

  postgis:
    image: rogalik/postgis
    ports:
      - "5555:5432"
    container_name: postgres_geoserver
    environment:
      POSTGRES_USER: geoserver
      POSTGRES_PASSWORD: geoserver
    volumes:
      - ./postgis/postgresql_data:/var/lib/postgresql/data:Z
    healthcheck:
      test: pg_isready -U geoserver -h localhost -t 5 || exit 1
      interval: 10s
      retries: 5
      timeout: 10s
    networks:
      - mapstore-network

volumes:
  pg_data:

